function qpd = D2q1_desired(in1,in2,in3,in4,g)
%D2Q1_DESIRED
%    QPD = D2Q1_DESIRED(IN1,IN2,IN3,IN4,G)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    21-May-2015 15:59:29

Dthe1 = in2(4,:);
Dthe2 = in2(5,:);
Dthe3 = in2(6,:);
mass1 = in3(1,:);
mass2 = in3(2,:);
mass3 = in3(3,:);
qad1 = in1(1,:);
qad2 = in1(2,:);
r1 = in4(1,:);
r2 = in4(2,:);
r3 = in4(3,:);
the1 = in2(1,:);
the2 = in2(2,:);
the3 = in2(3,:);
t2 = r2.^2;
t3 = cos(the2);
t4 = sin(the2);
t5 = the2+the3;
t6 = mass2.*r2.*t4;
t7 = mass3.*r2.*t4.*2.0;
t8 = sin(t5);
t9 = mass3.*r3.*t8;
t10 = t6+t7+t9;
t11 = sin(the3);
t12 = mass3.*r1.*r3.*t8.*(1.0./2.0);
t13 = the1+the2;
t14 = cos(t13);
t15 = cos(the1);
t16 = r1.*t15;
t17 = cos(t5);
t18 = cos(the3);
t19 = r1.*t8;
t20 = r2.*t11;
t21 = t19+t20;
t22 = r1.^2;
t23 = mass2.*t2.*(1.0./3.0);
t24 = mass3.*t2;
t25 = r3.^2;
t26 = mass3.*t25.*(1.0./3.0);
t27 = mass3.*r2.*r3.*t18;
qpd = (-Dthe2.*(Dthe1.*r1.*t10.*(1.0./2.0)+Dthe2.*r1.*t10.*(1.0./2.0)+Dthe3.*mass3.*r3.*t21.*(1.0./2.0))-Dthe1.*(Dthe3.*(t12+mass3.*r2.*r3.*t11.*(1.0./2.0))+Dthe2.*(t12+mass2.*r1.*r2.*t4.*(1.0./2.0)+mass3.*r1.*r2.*t4))+qad1.*(t23+t24+t26+t27+mass2.*r1.*r2.*t3.*(1.0./2.0)+mass3.*r1.*r2.*t3+mass3.*r1.*r3.*t17.*(1.0./2.0))+g.*mass3.*(t16+r2.*t14+r3.*cos(the1+the2+the3).*(1.0./2.0))+g.*mass2.*(t16+r2.*t14.*(1.0./2.0))+g.*mass1.*r1.*t15.*(1.0./2.0)+mass3.*qad2.*r3.*(r3.*2.0+r1.*t17.*3.0+r2.*t18.*3.0).*(1.0./6.0)-Dthe3.*mass3.*r3.*t21.*(Dthe1+Dthe2+Dthe3).*(1.0./2.0))./(t23+t24+t26+t27+mass1.*t22.*(1.0./3.0)+mass2.*t22+mass3.*t22+mass2.*r1.*r2.*t3+mass3.*r1.*r2.*t3.*2.0+mass3.*r1.*r3.*t17);
