function out1 = ddr(in1,in2,g,k_spring,in5,in6)
%DDR
%    OUT1 = DDR(IN1,IN2,G,K_SPRING,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    22-May-2015 11:35:40

Dthe1 = in1(5,:);
Dthe2 = in1(6,:);
mass1 = in2(1,:);
mass2 = in2(2,:);
r1 = in1(3,:);
r01 = in5(1,:);
r2 = in1(4,:);
r02 = in5(2,:);
tau2 = in6(2,:);
the1 = in1(1,:);
the2 = in1(2,:);
t2 = r1.^2;
t3 = the2.*2.0;
t4 = Dthe1.^2;
t5 = r2.^2;
t6 = cos(the2);
t7 = mass1.^2;
t8 = cos(t3);
t9 = mass2.^2;
t10 = sin(the1);
t11 = Dthe2.^2;
t12 = 1.0./mass1;
t13 = 1.0./r1;
t14 = 1.0./r2;
t15 = sin(the2);
t16 = sin(t3);
t17 = t6.^2;
t18 = cos(the1);
out1 = [(t12.*t13.*t14.*(k_spring.*mass1.*r2.*t2.*2.4e1+k_spring.*mass2.*r2.*t2.*9.0-mass1.*r1.*t15.*tau2.*3.6e1+mass2.*r2.*t16.*tau2.*9.0-r2.*t2.*t4.*t7.*8.0-k_spring.*mass1.*r1.*r01.*r2.*2.4e1-k_spring.*mass2.*r1.*r01.*r2.*9.0-k_spring.*mass1.*r1.*t5.*t6.*4.8e1-k_spring.*mass2.*r1.*t5.*t6.*3.6e1+k_spring.*mass2.*r2.*t2.*t8.*9.0+g.*r1.*r2.*t7.*t10.*1.2e1-mass1.*mass2.*r2.*t2.*t4.*6.0+r1.*t4.*t5.*t6.*t9.*3.0+r1.*t5.*t6.*t9.*t11.*3.0+k_spring.*mass1.*r1.*r2.*r02.*t6.*4.8e1+k_spring.*mass2.*r1.*r2.*r02.*t6.*3.6e1-k_spring.*mass2.*r1.*r01.*r2.*t8.*9.0+mass1.*mass2.*r1.*t4.*t5.*t6.*4.0+mass1.*mass2.*r1.*t5.*t6.*t11.*4.0+g.*mass1.*mass2.*r1.*r2.*sin(t3+the1).*(3.0./2.0)+Dthe1.*Dthe2.*r1.*t5.*t6.*t9.*6.0+g.*mass1.*mass2.*r1.*r2.*t10.*(1.5e1./2.0)+Dthe1.*Dthe2.*mass1.*mass2.*r1.*t5.*t6.*8.0).*(-4.0./3.0))./(mass1.*8.0+mass2.*7.0-mass2.*t8);(t12.*t13.*t14.*(k_spring.*r1.*t5.*t7.*-2.4e1-k_spring.*r1.*t5.*t9.*7.2e1+r2.*t9.*t15.*tau2.*3.6e1-k_spring.*mass1.*mass2.*r1.*t5.*9.6e1-mass1.*mass2.*r1.*t16.*tau2.*9.0+mass1.*mass2.*r2.*t15.*tau2.*3.6e1+k_spring.*r1.*r2.*r02.*t7.*2.4e1+k_spring.*r1.*r2.*r02.*t9.*7.2e1+k_spring.*r2.*t2.*t6.*t9.*3.6e1+mass2.*r1.*t4.*t5.*t7.*8.0+mass1.*r1.*t4.*t5.*t9.*1.4e1+mass2.*r1.*t4.*t5.*t9.*6.0+mass2.*r1.*t5.*t7.*t11.*8.0+mass1.*r1.*t5.*t9.*t11.*1.4e1+mass2.*r1.*t5.*t9.*t11.*6.0-k_spring.*r1.*r01.*r2.*t6.*t9.*3.6e1-mass2.*r2.*t2.*t4.*t6.*t7.*4.0-mass1.*r2.*t2.*t4.*t6.*t9.*3.0+Dthe1.*Dthe2.*mass2.*r1.*t5.*t7.*1.6e1+Dthe1.*Dthe2.*mass1.*r1.*t5.*t9.*2.8e1+Dthe1.*Dthe2.*mass2.*r1.*t5.*t9.*1.2e1+k_spring.*mass1.*mass2.*r1.*r2.*r02.*9.6e1+k_spring.*mass1.*mass2.*r2.*t2.*t6.*4.8e1-k_spring.*mass1.*mass2.*r1.*t5.*t17.*1.8e1-k_spring.*mass1.*mass2.*r1.*r01.*r2.*t6.*4.8e1+k_spring.*mass1.*mass2.*r1.*r2.*r02.*t17.*1.8e1+g.*mass2.*r1.*r2.*t6.*t7.*t10.*1.2e1+g.*mass1.*r1.*r2.*t6.*t9.*t10.*9.0+g.*mass2.*r1.*r2.*t7.*t15.*t18.*6.0+g.*mass1.*r1.*r2.*t9.*t15.*t18.*6.0).*(2.0./3.0))./(mass2.*(mass1.*4.0+mass2.*4.0-mass2.*t17))];
