function y = map2TaskSpace(in1,mass1,r1,g)
%MAP2TASKSPACE
%    Y = MAP2TASKSPACE(IN1,MASS1,R1,G)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    05-Jun-2015 17:21:05

r1 = in1(2,:);
the1 = in1(1,:);
t2 = cos(the1);
t3 = r1.^2;
t4 = sin(the1);
y = [sqrt(t2.^2.*t3+t3.*t4.^2);r1];
